[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = "0.6.3"
http = "0.2.8"
lambda_runtime = "0.6.0"
serde = "1.0.140"
serde_json = "1.0.82"
tokio = { version = "1.20.1", features = ["full"] }
