service: rust-lambda
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  memorySize: 128
  region: us-east-1
  httpApi:
    payload: '2.0'
    shouldStartNameWithService: true
    metrics: true
    cors: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:*
          Resource: '*'

  environment:
    ENVIRONMENT: ${opt:stage, 'local'}

package:
  individually: true

functions:
  rust:
    handler: functions/api.api
    runtime: provided.al2
    tags:
      rust: true
    events:
      - httpApi: '*'

plugins:
  - sls-rust
