[package]
name = "api"
version = "0.1.0"
edition = "2021"

[package.metadata.commands]
dev = "bash -c \"source .env && cargo watch -x 'run'\""

[dependencies]
actix-web = "4.1.0"
lambda-web = { version = "0.2.0", features = ["actix4"] }
serde = "1.0.140"
serde_json = "1.0.82"
