service: rust-lambda
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  memorySize: 128
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:*
          Resource: '*'

  environment:
    ENVIRONMENT: ${opt:stage, 'local'}

package:
  individually: true

functions:
  rust:
    handler: functions/api.api
    runtime: provided.al2
    tags:
      rust: true

custom:
  # localstack
  localstack:
    stages:
      - local
    host: http://0.0.0.0

plugins:
  - sls-rust
  - serverless-localstack
